object RegexPattern {
    val jePyeon = Regex("^제[0-9]+편")
    val numberDotNumber = Regex("^[0-9]+.[0-9]+")
    val burok = Regex("^부록")
    val jeJang = Regex("^제[0-9]+장")
    val pyeon = Regex("^[가-힣]+편")
    val jang = Regex("^[0-9]+장")
    val jeBu = Regex("^제[0-9]+부")
    val partSpaceNumber = Regex("^Part [0-9]+")
    val number = Regex("^[0-9]+")
    val CHAPTERSpaceNumber = Regex("^CHAPTER [0-9]+")
    val ChapterSpaceNumber = Regex("^Chapter [0-9]+")
    val nothing = Regex("^[가-힣a-zA-Z]+")
    val number_number = Regex("^[0-9]+-[0-9]+")
    val underbar2 = Regex("^_{2}")
    val underbar4 = Regex("^_{4}")
    val brackets = Regex("^\\[[가-힣]+\\]")
    val burokAlphabet = Regex("^부록 [A-Za-z]")
    val CHAPTERNumber = Regex("^CHAPTER[0-9]+")
    val ChapterNumber = Regex("^Chapter[0-9]+")
    val numberDot = Regex("^[0-9]+.")
    val PartNumber = Regex("^Part[0-9]+")
    val jjaeMadang = Regex("^[가-힣]+째마당")
}