/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ejjang2030.bookcontentparserlib;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
